### ISSUE TITLE
New chromedriver download

### ISSUE THREAD

**Issue by asaf400** [snapfast/AutoMates#4]
https://chromedriver.chromium.org/downloads/version-selection#h.4wiyvw42q63v

The chromium decided to change the way they publish new versions of the chrome driver starting at version 115, so this breaks the automated chromedriver download & setup.

**Comment by asaf400** [comment]
I was able to overcome this by not giving any path to:
`service = Service(local_bin_directory + '/chromedriver/chromedriver')`

Like so:
`service = Service()`

I think selenium takes care of the driver now "automagically" ?

**Comment by AbhishekAme22** [comment]
> I was able to overcome this by not giving any path to: `service = Service(local_bin_directory + '/chromedriver/chromedriver')`
> 
> Like so: `service = Service()`
> 
> I think selenium takes care of the driver now "automagically" ?

not working in my case

**Comment by asaf400** [comment]
You can try and make sure to download the latest chromedirver and chrome, 
the location of the downloads have changed:

https://googlechromelabs.github.io/chrome-for-testing/#stable

**Comment by AbhishekAme22** [comment]
Upgrading selenium to 112 works for me

**Comment by snapfast** [comment]
Thanks for opening this issue. I have started looking into it. 
Soon a fix for code will be added.

**Comment by snapfast** [comment]
Updated.
